Fixed bug in gpm/bin/track_task.py due to new database name containing a hyphen. Also changed all calls to that script to ensure it uses the version *outside* the container

diff --git a/templates/giantsquid_download.tmpl b/templates/giantsquid_download.tmpl
--- a/templates/giantsquid_download.tmpl
+++ b/templates/giantsquid_download.tmpl
@@ -6,18 +6,25 @@ set -x
 obsnum=$1
 
 # Mark start of download in database
-track_task.py start --jobid="${SLURM_ARRAY_JOB_ID}" --taskid="${SLURM_ARRAY_TASK_ID}" --start_time="$(date +%s)"
+$GPMBASE/gpm/bin/track_task.py start --jobid="${SLURM_ARRAY_JOB_ID}" --taskid="${SLURM_ARRAY_TASK_ID}" --start_time="$(date +%s)"
 
 if [[ -z $obsnum ]]
 then
     echo "No obsid passed to giant-squid download script. Not downloading anything."
-    track_task.py fail --jobid="${SLURM_ARRAY_JOB_ID}" --taskid="${SLURM_ARRAY_TASK_ID}" --finish_time="$(date +%s)"
+    $GPMBASE/gpm/bin/track_task.py fail --jobid="${SLURM_ARRAY_JOB_ID}" --taskid="${SLURM_ARRAY_TASK_ID}" --finish_time="$(date +%s)"
     exit 1
 fi
 
 cd "${GPMSCRATCH}" || exit 1
 
 project=$(${GPMBASE}/gpm_track.py obs_epoch --obs_id $obsnum)
+
+if [[ -z $project ]]
+then
+    echo "'project' is empty. Perhaps the connection to the database failed...?"
+    $GPMBASE/gpm/bin/track_task.py fail --jobid="${SLURM_ARRAY_JOB_ID}" --taskid="${SLURM_ARRAY_TASK_ID}" --finish_time="$(date +%s)"
+    exit 1
+fi
 
 # Ensure that the target download directory exists and cd into it
 mkdir -p "${project}/${obsnum}" && cd "${project}/${obsnum}"
@@ -26,7 +33,7 @@ mkdir -p "${project}/${obsnum}" && cd "${project}/${obsnum}"
 if [[ -d "${obsnum}.ms" ]]
 then
     echo "${obsnum}.ms already exists; please remove directory before trying to (re)download."
-    track_task.py fail --jobid="${SLURM_ARRAY_JOB_ID}" --taskid="${SLURM_ARRAY_TASK_ID}" --finish_time="$(date +%s)"
+    $GPMBASE/gpm/bin/track_task.py fail --jobid="${SLURM_ARRAY_JOB_ID}" --taskid="${SLURM_ARRAY_TASK_ID}" --finish_time="$(date +%s)"
     exit 1
 fi
 
@@ -41,12 +48,12 @@ grep -v birli_manifest.sha1sum birli_manifest.sha1sum | sha1sum -c
 # Check if the download was successful
 if [[ $? -ne 0 ]] # i.e. if it failed
 then
-    track_task.py fail --jobid="${SLURM_ARRAY_JOB_ID}" --taskid="${SLURM_ARRAY_TASK_ID}" --finish_time="$(date +%s)"
+    $GPMBASE/gpm/bin/track_task.py fail --jobid="${SLURM_ARRAY_JOB_ID}" --taskid="${SLURM_ARRAY_TASK_ID}" --finish_time="$(date +%s)"
     exit 1
 fi
 
 # The tar file has been successfully extracted, so remove it
 rm ${obsnum}_*_ms.tar
 
-track_task.py finish --jobid="${SLURM_ARRAY_JOB_ID}" --taskid="${SLURM_ARRAY_TASK_ID}" --finish_time="$(date +%s)"
+$GPMBASE/gpm/bin/track_task.py finish --jobid="${SLURM_ARRAY_JOB_ID}" --taskid="${SLURM_ARRAY_TASK_ID}" --finish_time="$(date +%s)"
 
