added check_solutions, obsid -> calid,

diff --git a/templates/gpmonim.tmpl b/templates/gpmonim.tmpl
--- a/templates/gpmonim.tmpl
+++ b/templates/gpmonim.tmpl
@@ -5,7 +5,7 @@
 set -x
 
 pipeuser=PIPEUSER
-obsnum=OBSNUM
+calid=CALID
 datadir=DATADIR
 
 # Retrieving unusual variables so that we can easily resubmit the job to check all the data was processed
@@ -15,25 +15,34 @@ error=ERROR
 account=ACCOUNT
 queue=QUEUE
 
-epoch=$(determine_epoch.py --obsid $obsnum)
-epoch="Epoch"$epoch
-datadir=$datadir/$epoch
-cd $datadir
+epoch=$(determine_epoch.py --obsid $calid)
+epoch="Epoch${epoch}"
+datadir="${datadir}/${epoch}"
 
-# TODO: Insert test of calibration quality here. Only if the calibrator is good enough, proceed to the next step
-cd $obsnum
+cd $datadir || exit 1
 
-# result=$(tim_calibration_quality_check.py)
-# if result...
+# Test to see if the calibration solution meets minimum quality control. At the moment
+# this is a simple check based on the number of flagged solutions
+SOLUTIONS="${calid}/${calid}solutions_initial_ref.bin"
 
-cd ../
+# Need to confirm the python script works
+result=$(check_solutions.py -t 0.25 -s 4 "${SOLUTIONS}")
+if echo "${result}" | grep -q fail
+then
+    mv "${SOLUTIONS}" "${SOLUTIONS%.bin}_ref_failed.bin"
+    echo "Calibration solutions file failed checks. Exiting. "
+
+    # Email goes here
+
+    exit 111
+fi
 # Find all the observations taken within +/-12h of that calibrator
 # That have not yet been processed, as recorded by our database
-obsid=$(gp_monitor_lookup.py --calid $obsnum)
+obsids=$(gp_monitor_lookup.py --calid $calid)
 
-if [[ $obsid != ""]]
+if [[ $obsids != "" ]]
 then
-    for obs in $obsid
+    for obs in $obsids
     do
     # TODO: add the track_gp.py that tells our tracking database that we are now working on this obsid
         dep=($(obs_manta.sh -p $epoch -o $obs))
