Added (draft of) downstream processing of I and V images

diff --git a/templates/postimage.tmpl b/templates/postimage.tmpl
--- a/templates/postimage.tmpl
+++ b/templates/postimage.tmpl
@@ -4,6 +4,7 @@ set -x
 
 pipeuser=PIPEUSER
 obsnum=OBSNUM
+pol=POL
 
 # If obsnum is a file, then we are in an array job
 if [[ -f ${obsnum} ]]
@@ -25,12 +26,12 @@ echo "taskid: ${taskid}"
 function test_fail {
     if [[ $1 != 0 ]]
     then
-        ${GPMBASE}/gpm/bin/track_task.py fail --jobid="${jobid}" --taskid="${taskid}" --finish_time="$(date +%s)"
+        track_task.py fail --jobid="${jobid}" --taskid="${taskid}" --finish_time="$(date +%s)"
         exit "$1"
     fi
 }
 
-${GPMBASE}/gpm/bin/track_task.py start --jobid="${jobid}" --taskid="${taskid}" --start_time="$(date +%s)"
+track_task.py start --jobid="${jobid}" --taskid="${taskid}" --start_time="$(date +%s)"
 
 # Makes fits_warp parallelisation work on Zeus
 # export KMP_INIT_AT_FORK=false
@@ -75,31 +76,31 @@ metafits=$(ls -t ${obsnum}*metafits* | head -1)
 
 for subchan in ${subchans}
 do
-    BMAJ=$(pyhead.py -p BMAJ "${obsnum}_deep-${subchan}-image-pb.fits" | awk '{print $3}' )
+    BMAJ=$(pyhead.py -p BMAJ "${obsnum}_deep-${subchan}-${pol}-image-pb.fits" | awk '{print $3}' )
     if [[ "$BMAJ" == "0"  ]]
     then
-        echo "${obsnum}_deep-${subchan}-image-pb.fits has zero-size PSF: something is broken!"
+        echo "${obsnum}_deep-${subchan}-${pol}-image-pb.fits has zero-size PSF: something is broken!"
         exit 1
     fi
     
-    if [[ ! -e "${obsnum}_deep-${subchan}-image-pb_comp.fits"  ]]
+    if [[ ! -e "${obsnum}_deep-${subchan}-${pol}-image-pb_comp.fits"  ]]
     then
         # The mask_image.py operation will destructively remove the pixels. I can not think of a case 
         # where we actually want to keep pixels below 5% of the PB, apart from _maybe_ causing non-uniform
         # noise issues in the swarp image. In any case, the below attempts to preserve the original image
         # as a just in case. 
-        if [[ ! -e "${obsnum}_deep-${subchan}-image-pb_original.fits" ]]
+        if [[ ! -e "${obsnum}_deep-${subchan}-${pol}-image-pb_original.fits" ]]
         then 
-            cp -v "${obsnum}_deep-${subchan}-image-pb.fits" "${obsnum}_deep-${subchan}-image-pb_original.fits"
+            cp -v "${obsnum}_deep-${subchan}-${pol}-image-pb.fits" "${obsnum}_deep-${subchan}-${pol}-image-pb_original.fits"
         fi
-        if [[ ! -e "${obsnum}_deep-${subchan}-image-pb.fits" ]]
+        if [[ ! -e "${obsnum}_deep-${subchan}-${pol}-image-pb.fits" ]]
         then 
-            if [[ ! -e "${obsnum}_deep-${subchan}-image-pb_original.fits" ]]
+            if [[ ! -e "${obsnum}_deep-${subchan}-${pol}-image-pb_original.fits" ]]
             then 
-                echo "Missing ${obsnum}_deep-${subchan}-image-pb.fits file, and no copy found. This should not happen. "
+                echo "Missing ${obsnum}_deep-${subchan}-${pol}-image-pb.fits file, and no copy found. This should not happen. "
                 test_fail 2
             fi
-            cp -v "${obsnum}_deep-${subchan}-image-pb_original.fits" "${obsnum}_deep-${subchan}-image-pb.fits"
+            cp -v "${obsnum}_deep-${subchan}-${pol}-image-pb_original.fits" "${obsnum}_deep-${subchan}-${pol}-image-pb.fits"
         fi
         
 
@@ -120,21 +121,21 @@ do
 #            ((cstart+=1))
 #            ((cend+=1))
         lookup_beam.py "${obsnum}" \
-        "_deep-${subchan}-image-pb.fits" \
-        "${obsnum}_deep-${subchan}-image-pb-" \
+        "_deep-${subchan}-${pol}-image-pb.fits" \
+        "${obsnum}_deep-${subchan}-${pol}-image-pb-" \
         -c "$cstart-$cend"
 
-        mask_image.py "${obsnum}_deep-${subchan}-image-pb.fits" \
-        "${obsnum}_deep-${subchan}-image-pb-XX-beam.fits" \
-        "${obsnum}_deep-${subchan}-image-pb-YY-beam.fits" \
+        mask_image.py "${obsnum}_deep-${subchan}-${pol}-image-pb.fits" \
+        "${obsnum}_deep-${subchan}-${pol}-image-pb-XX-beam.fits" \
+        "${obsnum}_deep-${subchan}-${pol}-image-pb-YY-beam.fits" \
         --apply-mask -v
 
         # move into place the new masked image
-        rm "${obsnum}_deep-${subchan}-image-pb.fits" && mv "${obsnum}_deep-${subchan}-image-pb_mask.fits" "${obsnum}_deep-${subchan}-image-pb.fits"
+        rm "${obsnum}_deep-${subchan}-${pol}-image-pb.fits" && mv "${obsnum}_deep-${subchan}-${pol}-image-pb_mask.fits" "${obsnum}_deep-${subchan}-${pol}-image-pb.fits"
 
-        BANE --cores ${GXNCPUS} --compress --noclobber "${obsnum}_deep-${subchan}-image-pb.fits"
+        BANE --cores ${GXNCPUS} --compress --noclobber "${obsnum}_deep-${subchan}-${pol}-image-pb.fits"
         # TODO: Replace the redirection
-        aegean --cores 1 --autoload --table="./${obsnum}_deep-${subchan}-image-pb.fits" "./${obsnum}_deep-${subchan}-image-pb.fits" > >(tee -a "${obsnum}_deep-${subchan}_aegean.log") 2> >(tee -a "${obsnum}_deep-${subchan}_aegean.log" >&2)
+        aegean --cores 1 --autoload --table="./${obsnum}_deep-${subchan}-${pol}-image-pb.fits" "./${obsnum}_deep-${subchan}-${pol}-image-pb.fits" > >(tee -a "${obsnum}_deep-${subchan}_aegean.log") 2> >(tee -a "${obsnum}_deep-${subchan}_aegean.log" >&2)
     fi
     nsrc=$(grep "INFO found" "${obsnum}_deep-${subchan}_aegean.log" | head -1 | awk '{print $3}')
     if [[ $nsrc -lt $minsrcs ]]
@@ -144,7 +145,7 @@ do
         RA=$( pyhead.py -p RA "${obsnum}.metafits" | awk '{print $3}' )
         Dec=$( pyhead.py -p DEC "${obsnum}.metafits" | awk '{print $3}' )
         chan=$( pyhead.py -p CENTCHAN "${obsnum}.metafits" | awk '{print $3}' )
-        mid=$( pyhead.py -p CRVAL3 "${obsnum}_deep-${subchan}-image-pb.fits" | awk '{print $3}' )
+        mid=$( pyhead.py -p CRVAL3 "${obsnum}_deep-${subchan}-${pol}-image-pb.fits" | awk '{print $3}' )
         freqq=$(echo "$mid" | awk '{printf "%03.0f",($1)/1e6}')
         
         # Roughly the centre and radius of the image:
@@ -155,7 +156,7 @@ do
         if [[ ! -e "${obsnum}_${subchan}_complete_sources_xm.fits" ]]
         then
             fits_warp.py \
-            --incat "${obsnum}_deep-${subchan}-image-pb_comp.fits" \
+            --incat "${obsnum}_deep-${subchan}-${pol}-image-pb_comp.fits" \
             --refcat "${POS_MODEL_CATALOGUE}" \
             --xm "${obsnum}_${subchan}_complete_sources_xm.fits" \
             --plot \
@@ -163,17 +164,17 @@ do
             --dec1 dec \
             --ra2 RAJ2000 \
             --dec2 DEJ2000 \
-            --infits "${obsnum}_deep-${subchan}-image-pb.fits"
+            --infits "${obsnum}_deep-${subchan}-${pol}-image-pb.fits"
         fi
         
-        if [[ ! -e "${obsnum}_deep-${subchan}-image-pb_warp.fits" ]]
+        if [[ ! -e "${obsnum}_deep-${subchan}-${pol}-image-pb_warp.fits" ]]
         then
-            fits_warp.py --incat "./${obsnum}_deep-${subchan}-image-pb_comp.fits" \
+            fits_warp.py --incat "./${obsnum}_deep-${subchan}-${pol}-image-pb_comp.fits" \
             --refcat "${POS_MODEL_CATALOGUE}" \
-            --corrected "./${obsnum}_deep-${subchan}-image-pb_comp_warp-corrected.fits" \
+            --corrected "./${obsnum}_deep-${subchan}-${pol}-image-pb_comp_warp-corrected.fits" \
             --xm "./${obsnum}_${subchan}_fits_warp_xm.fits" \
             --suffix warp \
-            --infits "./${obsnum}_deep-${subchan}-image-pb.fits" \
+            --infits "./${obsnum}_deep-${subchan}-${pol}-image-pb.fits" \
             --ra1 ra --dec1 dec \
             --ra2 RAJ2000 --dec2 DEJ2000 \
             --plot \
@@ -192,7 +193,7 @@ do
             # flux_wrap dependency here
             # Match the image catalogue to the model table:
             match_catalogues \
-            "${obsnum}_deep-${subchan}-image-pb_comp_warp-corrected.fits" \
+            "${obsnum}_deep-${subchan}-${pol}-image-pb_comp_warp-corrected.fits" \
             "${FLUX_MODEL_CATALOGUE}" \
             --separation "${separation}" \
             --exclusion_zone "${exclusion}" \
@@ -212,12 +213,12 @@ do
             # GLEAM-X options
             #--mode mean \
             #--update-bscale \
-#        if [[ ! -e "${obsnum}_deep-${subchan}-image-pb_warp_${method}_cf_output.txt" ]]
-        if [[ ! -e "${obsnum}_deep-${subchan}-image-pb_warp_unscaled.fits" ]]
+#        if [[ ! -e "${obsnum}_deep-${subchan}-${pol}-image-pb_warp_${method}_cf_output.txt" ]]
+        if [[ ! -e "${obsnum}_deep-${subchan}-${pol}-image-pb_warp_unscaled.fits" ]]
         then
             flux_warp \
             "${obsnum}_${subchan}_xm.fits" \
-            "${obsnum}_deep-${subchan}-image-pb_warp.fits" \
+            "${obsnum}_deep-${subchan}-${pol}-image-pb_warp.fits" \
             --freq "${freqq}" \
             --threshold 0.1 \
             --mode=linear_screen \
@@ -241,29 +242,29 @@ do
             --nolatex
         fi
         # The _scaled stem will break onward processing so move the filenames around
-        mv ${obsnum}_deep-${subchan}-image-pb_warp.fits ${obsnum}_deep-${subchan}-image-pb_warp_unscaled.fits
-        mv ${obsnum}_deep-${subchan}-image-pb_warp_scaled.fits ${obsnum}_deep-${subchan}-image-pb_warp.fits
+        mv ${obsnum}_deep-${subchan}-${pol}-image-pb_warp.fits ${obsnum}_deep-${subchan}-${pol}-image-pb_warp_unscaled.fits
+        mv ${obsnum}_deep-${subchan}-${pol}-image-pb_warp_scaled.fits ${obsnum}_deep-${subchan}-${pol}-image-pb_warp.fits
         # Compress the scaling image so I can apply it to the RMS and BKG images
-        factor=$(pyhead.py -p BN_CFAC "${obsnum}_deep-${subchan}-image-pb_rms.fits" | awk '{print $3}')
-        SR6 -f $factor -o ${obsnum}_deep-${subchan}-image-pb_warp_scaled_cf_sr6.fits ${obsnum}_deep-${subchan}-image-pb_warp_scaled_cf.fits
-        python3 $GXBASE/gleam_x/bin/divide.py ${obsnum}_deep-${subchan}-image-pb_rms.fits ${obsnum}_deep-${subchan}-image-pb_warp_scaled_cf_sr6.fits ${obsnum}_deep-${subchan}-image-pb_warp_rms.fits
-        python3 $GXBASE/gleam_x/bin/divide.py ${obsnum}_deep-${subchan}-image-pb_bkg.fits ${obsnum}_deep-${subchan}-image-pb_warp_scaled_cf_sr6.fits ${obsnum}_deep-${subchan}-image-pb_warp_bkg.fits
+        factor=$(pyhead.py -p BN_CFAC "${obsnum}_deep-${subchan}-${pol}-image-pb_rms.fits" | awk '{print $3}')
+        SR6 -f $factor -o ${obsnum}_deep-${subchan}-${pol}-image-pb_warp_scaled_cf_sr6.fits ${obsnum}_deep-${subchan}-${pol}-image-pb_warp_scaled_cf.fits
+        python3 $GXBASE/gleam_x/bin/divide.py ${obsnum}_deep-${subchan}-${pol}-image-pb_rms.fits ${obsnum}_deep-${subchan}-${pol}-image-pb_warp_scaled_cf_sr6.fits ${obsnum}_deep-${subchan}-${pol}-image-pb_warp_rms.fits
+        python3 $GXBASE/gleam_x/bin/divide.py ${obsnum}_deep-${subchan}-${pol}-image-pb_bkg.fits ${obsnum}_deep-${subchan}-${pol}-image-pb_warp_scaled_cf_sr6.fits ${obsnum}_deep-${subchan}-${pol}-image-pb_warp_bkg.fits
 
-        #factor=$(pyhead.py -p BSCALE "${obsnum}_deep-${subchan}-image-pb_warp.fits" | awk '{print $3}')
+        #factor=$(pyhead.py -p BSCALE "${obsnum}_deep-${subchan}-${pol}-image-pb_warp.fits" | awk '{print $3}')
         
         # The RMS and BKG maps will not have changed much from the ionospheric warping, so I can just
         # rename them and update BSCALE
-        #mv "${obsnum}_deep-${subchan}-image-pb_rms.fits" "${obsnum}_deep-${subchan}-image-pb_warp_rms.fits"
-        #mv "${obsnum}_deep-${subchan}-image-pb_bkg.fits" "${obsnum}_deep-${subchan}-image-pb_warp_bkg.fits"
-        #pyhead.py -u BSCALE "$factor" "${obsnum}_deep-${subchan}-image-pb_warp_bkg.fits"
-        #pyhead.py -u BSCALE "$factor" "${obsnum}_deep-${subchan}-image-pb_warp_rms.fits"
+        #mv "${obsnum}_deep-${subchan}-${pol}-image-pb_rms.fits" "${obsnum}_deep-${subchan}-${pol}-image-pb_warp_rms.fits"
+        #mv "${obsnum}_deep-${subchan}-${pol}-image-pb_bkg.fits" "${obsnum}_deep-${subchan}-${pol}-image-pb_warp_bkg.fits"
+        #pyhead.py -u BSCALE "$factor" "${obsnum}_deep-${subchan}-${pol}-image-pb_warp_bkg.fits"
+        #pyhead.py -u BSCALE "$factor" "${obsnum}_deep-${subchan}-${pol}-image-pb_warp_rms.fits"
         
         # rerun the source-finding -- don't save to the log this time as the numbers should not have changed
-        if [[ ! -e "${obsnum}_deep-${subchan}-image-pb_warp_comp.fits" ]]
+        if [[ ! -e "${obsnum}_deep-${subchan}-${pol}-image-pb_warp_comp.fits" ]]
         then
-            aegean --cores 1 --autoload --table="./${obsnum}_deep-${subchan}-image-pb_warp.fits" "./${obsnum}_deep-${subchan}-image-pb_warp.fits"
+            aegean --cores 1 --autoload --table="./${obsnum}_deep-${subchan}-${pol}-image-pb_warp.fits" "./${obsnum}_deep-${subchan}-${pol}-image-pb_warp.fits"
         fi
-        if [[ ! -e "${obsnum}_deep-${subchan}-image-pb_warp_weight.fits" ]]
+        if [[ ! -e "${obsnum}_deep-${subchan}-${pol}-image-pb_warp_weight.fits" ]]
         then
             # Generate a weight map for mosaicking
             chans=($( pyhead.py -p CHANNELS "${obsnum}.metafits" | awk '{print $3}' | sed "s/,/ /g" ))
@@ -282,14 +283,14 @@ do
 #            ((cstart+=1))
 #            ((cend+=1))
             lookup_beam.py "${obsnum}" \
-            "_deep-${subchan}-image-pb_warp.fits" \
-            "${obsnum}_deep-${subchan}-image-pb_warp-" \
+            "_deep-${subchan}-${pol}-image-pb_warp.fits" \
+            "${obsnum}_deep-${subchan}-${pol}-image-pb_warp-" \
             -c "$cstart-$cend"
-            generate_weight_map.py "${obsnum}_deep-${subchan}-image-pb_warp-XX-beam.fits" \
-            "${obsnum}_deep-${subchan}-image-pb_warp-YY-beam.fits" \
-            "${obsnum}_deep-${subchan}-image-pb_warp_rms.fits"
+            generate_weight_map.py "${obsnum}_deep-${subchan}-${pol}-image-pb_warp-XX-beam.fits" \
+            "${obsnum}_deep-${subchan}-${pol}-image-pb_warp-YY-beam.fits" \
+            "${obsnum}_deep-${subchan}-${pol}-image-pb_warp_rms.fits"
         fi
     fi
 done
 
-${GPMBASE}/gpm/bin/track_task.py finish --jobid="${jobid}" --taskid="${taskid}" --finish_time="$(date +%s)"
+track_task.py finish --jobid="${jobid}" --taskid="${taskid}" --finish_time="$(date +%s)"
